name: Update GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: Run generate-stats (TypeScript)
        run: |
          corepack enable
          pnpm dlx tsx scripts/generate-stats.ts
        env:
          GH_STATS_TOKEN: ${{ secrets.GH_STATS_TOKEN }}

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add public/stats.json

          git diff --staged --quiet || git commit -m "chore: update github stats"

          git push